apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
    traefik.ingress.kubernetes.io/router.middlewares: default-qbittorrent-stripprefix-traefik@kubernetescrd
spec:
  rules:
    - host: home.hont.ro
      http:
        paths:
          - path: /qbittorrent
            pathType: Prefix
            backend:
              service:
                name: qbittorrent
                port:
                  number: 8080