apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le

spec:
  # tls:
  #   - hosts:
  #       - home.hont.ro
  #     secretName: home-hont-ro-tls
  rules:
    - host: home.hont.ro
      http:
        paths:
          - path: /prowlarr
            pathType: Prefix
            backend:
              service:
                name: prowlarr
                port:
                  number: 9696