apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - clusterissuer.yaml
  - ingress-qbittorrent.yaml
  - ingress-prowlarr.yaml
  - middleware-qbittorrent.yaml
  - middleware-prowlarr.yaml
namespace: default
nameSuffix: -traefik