apiVersion: v1
kind: Service
metadata:
  name: nitrox-subnautica
  namespace: default
spec:
  selector:
    app: nitrox-subnautica
  ports:
  ports:
    - protocol: TCP
      port: 11000
      targetPort: 11000
      nodePort: 30011 # Optional: Specify a fixed port (range: 30000-32767)
  type: NodePort

  