apiVersion: v1
kind: Service
metadata:
  name: nitrox-subnautica
  namespace: default
spec:
  selector:
    app: nitrox-subnautica
  ports:
    - protocol: UDP
      port: 11000
      targetPort: 11000