resources:
  - ../../infrastructure/namespaces
  - ../../infrastructure/nfs-provisioner
  - ../../infrastructure/storage
  - ../../infrastructure/networking/traefik
  # - ../../apps/media/sonarr
  # - ../../apps/media/radarr
  - ../../apps/media/prowlarr
  # - ../../apps/media/qbittorrent