apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
  annotations:
    fluxcd.io/automated: "true" # Enable automated image updates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          ports:
            - containerPort: 32400 # Plex Media Server
          env:
            - name: PLEX_CLAIM
              value: "claim-BaKwkHJKVeQzUvztPWsQ" # Optional: Add your Plex claim token here
            - name: ADVERTISE_IP
              value: "http://192.168.1.201:32400/" # Replace <your-server-ip> with your server's IP
            - name: TZ
              value: "Europe/Bucharest"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: media
              mountPath: /media
            - name: dri
              mountPath: /dev/dri # Add this to mount the GPU device
          securityContext:
            privileged: true # Required for device access
          livenessProbe:
            httpGet:
              path: /
              port: 32400
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: config
          hostPath:
            path: /mnt/internal_drive/config/plex
            type: DirectoryOrCreate
        - name: transcode
          hostPath:
            path: /mnt/internal_drive/transcode
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /media/external_drive/complete
            type: DirectoryOrCreate
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory # Add this volume definition for GPU mapping