apiVersion: v1
kind: Service
metadata:
  name: immich-origin-proxy
  labels:
    app: immich-origin-proxy
spec:
  type: ClusterIP
  selector:
    app: immich-origin-proxy
  ports:
    - name: http
      port: 8080
      targetPort: 8080
