apiVersion: v1
kind: Pod
metadata:
  name: volume-test-pv
  namespace: default
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: direct-volume
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: direct-volume
    nfs:
      server: nas.hont.ro
      path: /complete
    nfs:
      server: home.hont.ro
      path: /mnt/e/internalshare