all:
  hosts:
    home.hont.ro:
      ansible_user: ubuntu
  vars:
    homelab_timezone: Europe/Bucharest
    homelab_nas_host: nas.hont.ro
    homelab_nas_export: /complete
    homelab_nas_mountpoint: /media_nas/complete
