all:
  hosts:
    home.hont.ro:
      # Change this if your SSH username differs.
      ansible_user: dragos
  vars:
    homelab_timezone: Europe/Bucharest
    homelab_nas_host: nas.hont.ro
    homelab_nas_export: /complete
    homelab_nas_mountpoint: /media_nas/complete
