apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: default
spec:
  selector:
    app: homebridge
  ports:
    - protocol: TCP
      port: 8581
      targetPort: 8581
      nodePort: 30081
  type: NodePort
