apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: default
spec:
  selector:
    app: homebridge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8581
    - protocol: TCP
      port: 8582
      targetPort: 8582