apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: default
spec:
  selector:
    app: homebridge
  ports:
    - name: http  # <-- Add a unique name for this port
      protocol: TCP
      port: 80
      targetPort: 8581
    - name: secondary  # <-- Add a unique name for this port
      protocol: TCP
      port: 8582
      targetPort: 8582