resources:
  - ../../infrastructure/namespaces/media-namespace.yaml
  - ../../infrastructure/smb-csi
  - ../../infrastructure/storage/kustomization.yaml
  - ../../infrastructure/networking/traefik
  - ../../apps/media/sonarr
  - ../../apps/media/radarr
  - ../../apps/media/prowlarr
  - ../../apps/media/qbittorrent