apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-config-pv
    volumeAttributes:
      source: "//192.168.1.201/InternalDrive/config"
    nodeStageSecretRef:
      name: smbcreds
      namespace: default

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-internal-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-pv
    volumeAttributes:
      source: "//192.168.1.201/InternalDrive"
    nodeStageSecretRef:
      name: smbcreds
      namespace: default

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-internal-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-external-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-external-pv
    volumeAttributes:
      source: "//192.168.1.201/ExternalDrive"
    nodeStageSecretRef:
      name: smbcreds
      namespace: default

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-external-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb