apiVersion: v1
kind: Pod
metadata:
  name: smb-test-pod
  namespace: default
spec:
  containers:
  - name: smb-test-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do date >> /mnt/smb/outfile; sleep 5; done"]
    volumeMounts:
    - name: smb-internal-volume
      mountPath: /mnt/hostinternal
    - name: smb-external-volume
      mountPath: /mnt/hostexternal
  volumes:
  - name: smb-internal-volume
    persistentVolumeClaim:
      claimName: smb-internal-pvc
  - name: smb-external-volume
    persistentVolumeClaim:
      claimName: smb-external-pvc