apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/media/qbittorrent/
  - ../../apps/media/sonarr/
  - ../../apps/media/radarr/
  - ../../apps/media/prowlarr/
  - ../../apps/media/plex/
  - ../../apps/homeautomation/scrypted/
  - ../../apps/homeautomation/homebridge/
  - ../../apps/games/nitrox/

  - storage/