apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: default
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: amp-forge
spec:
  selector:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: amp-forge
  type: LoadBalancer
  ports:
    - name: amp-ui
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30088 # Expose AMP UI on a fixed NodePort
    - name: mc-server
      protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30065 # Expose Minecraft server on a fixed NodePort
  type: NodePort
  
 
