apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: default
spec:
  replicas: 1 # Updated to allow multiple pods
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          ports:
            - containerPort: 7878
          # env:
          #   - name: RADARR_URL
          #     value: "http://localhost:7878"
          #   - name: RADARR_API_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: radarr-secret
          #         key: api-key
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: radarr
            - name: complete
              mountPath: /complete
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
        - name: complete
          persistentVolumeClaim:
            claimName: complete-pvc